import os
import json
from datetime import datetime
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib.utils import simpleSplit
from database.models import PredictionHistory


class ReportService:
    def __init__(self):
        self.report_dir = os.path.join(os.getcwd(), "reports")
        os.makedirs(self.report_dir, exist_ok=True)

    def _draw_wrapped_text(self, pdf, label, value, x, y, max_width, line_height=18):
        text = f"{label}: {value}"
        lines = simpleSplit(text, "Helvetica", 11, max_width)
        for line in lines:
            pdf.drawString(x, y, line)
            y -= line_height
        return y

    def generate_prediction_report(self, history_id):
        record = PredictionHistory.query.get(history_id)

        if not record:
            raise ValueError("Prediction record not found")

        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        safe_name = record.patient_name.replace(" ", "_")
        filename = f"{safe_name}_{record.disease_type.replace(' ', '_').lower()}_{timestamp}.pdf"
        filepath = os.path.join(self.report_dir, filename)

        input_data = json.loads(record.input_data)

        pdf = canvas.Canvas(filepath, pagesize=A4)
        width, height = A4

        y = height - 50

        pdf.setFont("Helvetica-Bold", 18)
        pdf.drawString(170, y, "Health Prediction Report")

        y -= 40
        pdf.setFont("Helvetica-Bold", 13)
        pdf.drawString(50, y, "Patient Details")

        y -= 25
        pdf.setFont("Helvetica", 11)
        pdf.drawString(50, y, f"Patient Name: {record.patient_name}")
        y -= 20
        pdf.drawString(50, y, f"Age: {record.age}")
        y -= 20
        pdf.drawString(50, y, f"Gender: {record.gender}")
        y -= 20
        pdf.drawString(50, y, f"Disease Type: {record.disease_type}")
        y -= 20
        pdf.drawString(50, y, f"Generated On: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")

        y -= 35
        pdf.setFont("Helvetica-Bold", 13)
        pdf.drawString(50, y, "Prediction Summary")

        y -= 25
        pdf.setFont("Helvetica", 11)
        pdf.drawString(50, y, f"Prediction Result: {record.prediction_result}")
        y -= 20
        pdf.drawString(50, y, f"Confidence Score: {round(record.confidence * 100, 2)}%")
        y -= 20
        pdf.drawString(50, y, f"Risk Level: {record.risk_level}")
        y -= 20
        pdf.drawString(50, y, f"Record Created At: {record.created_at.strftime('%Y-%m-%d %H:%M:%S')}")

        y -= 35
        pdf.setFont("Helvetica-Bold", 13)
        pdf.drawString(50, y, "Input Parameters")

        y -= 25
        pdf.setFont("Helvetica", 11)

        for key, value in input_data.items():
            if y < 80:
                pdf.showPage()
                y = height - 50
                pdf.setFont("Helvetica", 11)

            label = key.replace("_", " ").title()
            y = self._draw_wrapped_text(pdf, label, value, 50, y, 500)
            y -= 4

        if y < 130:
            pdf.showPage()
            y = height - 50

        y -= 10
        pdf.setFont("Helvetica-Bold", 13)
        pdf.drawString(50, y, "Disclaimer")

        y -= 25
        pdf.setFont("Helvetica", 10)
        disclaimer = (
            "This report is generated by a machine learning based prediction system for academic "
            "and preliminary screening purposes only. It is not a final medical diagnosis. "
            "Please consult a qualified doctor or healthcare professional for proper medical advice."
        )
        lines = simpleSplit(disclaimer, "Helvetica", 10, 500)
        for line in lines:
            pdf.drawString(50, y, line)
            y -= 16

        pdf.save()

        return {
            "filename": filename,
            "filepath": filepath
        }


report_service = ReportService()